// <auto-generated />
namespace Coursat.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class ADD_COURSE_TABLE : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ADD_COURSE_TABLE));
        
        string IMigrationMetadata.Id
        {
            get { return "202005141539431_ADD_COURSE_TABLE"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
